version: "3.4"


services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: inf519
  cache:
    image: redis:5-buster
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'

volumes:
  volume-postgres:
