version: "3"

volumes:
  volume-postgres:

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: inf5190
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
